//calling in express to use methods and functionality
const express = require('express')
const { findOneAndReplace } = require('../models/bookModel.js')

//call in functions from bookController
const { getBooks, getBook, createBook, updateBook, deleteBook } = require('../controllers/bookController.js')

//set up router insatnce
const router = express.Router()

//define api endpoints
router.get('/', getBooks) //getting all books doesnt need a parameter
router.get('/:id', getBook) //need a specific book so require the id of the book
router.post('/', createBook) //no required id as its autogenerated
router.put('/:id', updateBook) //need the id of the book to update
router.delete('/:id', deleteBook) //need the id of the book to delete

module.exports = router